var tableauQuestion = [
        {   question : "Se Estiver a conduzir a 80 kmh, e se aproxima de uma área residencial, isso significa que:",
            propositionA : "Terá que acelerar a frente",
            propositionB : "Pode acelerar contanto que não existam outros carros",
            propositionC : "Terá que diminuir a velocidade logo a frente",
            propositionD : "Pode manter sua velocidade",
            reponse : "C"},
                    
        {   question : "Ao virar à esquerda em um sinal verde, vê que um pedestre está a cruzar. Quem tem o direito de passagem?",
            propositionA : "O pedestre, porque eles podem atravessar a estrada com qualquer sinal",
            propositionB : "O seu veículo porque o sinal está verde",
            propositionC : "O pedestre, porque ele atravessa o sinal verde",
            propositionD : "Seu veículo, porque os veículos tem direitos de passagem",
            reponse : "B"},
                    
        {   question : "A menos que dito, a velocidade máxima em uma área residencial é ____ kmh.",
            propositionA : "50",
            propositionB : "55",
            propositionC : "65",
            propositionD : "70",
            reponse : "A"},
            
            {   question : "Antes de mudar de faixa deverá:",
            propositionA : "Checar seus retrovisores",
            propositionB : "Checar os seus pontos cegos",
            propositionC : "Sinalizar suas intenções",
            propositionD : "Todas as alternativas anteriores",
            reponse : "D"},
                    
            {   question : "Qual o limite de álcool no sangue?",
            propositionA : "0.05%",
            propositionB : "0.18%",
            propositionC : "0.08%",
            propositionD : "0.06%",
            reponse : "C"},
                    
            {   question : "Deve parar e estacionar enquanto uma ambulância está passando a menos que",
            propositionA : "Esteja com pressa",
            propositionB : "Exista faixa vazia pra ela",
            propositionC : "Esteja em uma zona escolar",
            propositionD : "Esteja em uma interseção",
            reponse : "B"},
            
            {   question : "O direito de passagem deve ser cedido aos veículos de emergência quando:",
            propositionA : "Em todo momento",
            propositionB : "Luzes vermelhas, azuis ou brancas intermitentes",
            propositionC : "Usando uma sirene ou piscando luzes vermelhas, azuis ou brancas",
            propositionD : "Usando uma sirene",
            reponse : "C"},
                    
            {   question : "Qual das seguintes condições é permitida ao passar por outro veículo?",
            propositionA : "Seguir bem de perto",
            propositionB : "Saindo da estrada principal percorrida",
            propositionC : "Conduzir no lado oposto da rodovia",
            propositionD : "Excedendo o limite de velocidade",
            reponse : "C"},
                    
            {   question : "Está a conduzir em uma auto-estrada com um limite de velocidade de 110 kmh. A maioria do tráfego está viajando a 120 kmh, então não deve conduzir mais rápido que:",
            propositionA : "80 kmh",
            propositionB : "40 kmh",
            propositionC : "50 kmh",
            propositionD : "110 kmh",
            reponse : "D"},
                    
            {   question : "Ao ser ultrapassado por outro veículo, é importante não:",
            propositionA : "Desacelerar",
            propositionB : "Checar seus retrovisores",
            propositionC : "Ficar a olhar para o outro motorista",
            propositionD : "Acelerar",
            reponse : "D"},
    ]
    
